### ISSUE TITLE
debugger

### ISSUE THREAD

**Issue by akasei** [akasei/Cyjon#1]
system nie dostarcza podstawowych informacji o zamkniętej aplikacji, gdy wystąpił błąd z jej udziałem

**Comment by akasei** [comment]
Podczas błędu wykonywania programu, wyświetlone zostaną podstawowe informacje.

**Comment by vpiotr** [comment]
podstawowe informacje najlepiej zrzucić do pliku (ostatecznie na ekran ze stronicowaniem).
- nazwa aplikacji 
- kod błędu (przyczyna)
- komunikat błędu
- data i czas wystąpienia błędu
- informacje diagnostyczne specyficzne dla błędu (np. rejestry przed wywołaniem funkcji systemowej)

**Comment by akasei** [comment]
W tym momencie nie da się tego osiągnąć :/
