### ISSUE TITLE
moko i obsługa Ctrl

### ISSUE THREAD

**Issue by vpiotr** [akasei/Cyjon#10]
Obsługa klawiatury w moko nie odróżnia klawiszy z Ctrl i bez.

Efekty:
- ignorowanie stanu Ctrl np. w: Ctrl+Enter = Enter i Ctrl+Delete = Delete
- możliwość wywołania niechcianej kombinacji

Oczekiwany efekt: 
- brak działania przy naciśniętym Ctrl+Enter.
- odróżnianie klawiszy z i bez Ctrl

**Comment by akasei** [comment]
Ctrl jest klawisze specjalnym, wszystko nacisniete wraz z nim, jest przez niego zjadane :)

Takze, CTRL + Enter, Delete nie zostaly zaimplementowane.

Przemysli sie ten fakt.

**Comment by akasei** [comment]
Klawisz CTRL jest teraz ignorowany, jeśli zostanie wywołany z nieistniejącym skrótem.
