### ISSUE TITLE
moko - miganie ekranu

### ISSUE THREAD

**Issue by vpiotr** [akasei/Cyjon#12]
Ekran bardzo miga przy naciskaniu kolejnych klawiszy w moko.
Prawdopodobna przyczyna:  odrysowywanie przy każdym naciśniętym klawiszu.

**Comment by akasei** [comment]
Tak, ekran miga :) Zamiast aktualizoac ekran w miejscu gdzie wystapila zmiana, odswiezam caly ;) Zostanie to naprawione w niedalekim czasie.

**Comment by akasei** [comment]
"miganie" ekranu zostało już wyeliminowane w wersji gałęzi rozwojowej software/moko
