### ISSUE TITLE
klawiatura - cyfry zamiast poruszania kursorem

### ISSUE THREAD

**Issue by vpiotr** [akasei/Cyjon#13]
W konsoli, przy naciskaniu klawiszy kursora zamiast poruszania kursorem otrzymujemy cyfry,

Oczekiwany efekt:
- poziom 1 - minimalny: brak reakcji na klawisze kursora
- poziom 2: działające Left, Right i Insert (bez Insert Left/Right mają mały sens)
- poziom 3: działające Up/Down (poprzednia/następna komenda w historii komend)

Może być przydatne to: http://stackoverflow.com/questions/2876275/what-are-the-ascii-values-of-up-down-left-right

**Comment by akasei** [comment]
To jest typowo problem srodowiska MS Windows, na prawdziwym sprzecie tego nie uswiadczysz (nawet na GNU Linux dziala poprawnie).

**Comment by vpiotr** [comment]
To jest przede wszystkim problem z Cyjon (inne systemy-goście działają poprawnie). Prawdopodobnie pod Windows wirtualka inaczej generuje kody klawiatury (ale możliwe że nadal zgodnie z opisem interfejsu).

**Comment by akasei** [comment]
Jeśli błąd wystąpi na prawdziwym sprzęcie, naprawię.

**Comment by akasei** [comment]
Hmm, pod systemem MS/Windows 8+ problem w Bochs już nie występuje.
