### ISSUE TITLE
Correct IP address

### ISSUE THREAD

**Issue by Kwpolska** [akasei/Cyjon#23]
>     text_error	db	"Correct IP address.", VARIABLE_ASCII_CODE_RETURN
>     text_error	db	"Popraw adres IP.", VARIABLE_ASCII_CODE_RETURN

Komunikat angielski można odczytać jako „Poprawny adres IP”.  Lepiej:

> Invalid IP address. Niepoprawny adres IP.

**Comment by akasei** [comment]
Poprawione, https://github.com/akasei/Cyjon/commit/4b8bdc320da756af6985d89695f9e262a65c6614
