### ISSUE TITLE
liblary

### ISSUE THREAD

**Issue by jpacanowski** [akasei/Cyjon#28]
Nie powinno być library? :)

https://github.com/akasei/Cyjon/tree/reborn/**liblary**
https://github.com/akasei/Cyjon/blob/reborn/liblary/**liblary**_bit_find.asm
https://github.com/akasei/Cyjon/blob/reborn/liblary/**liblary**_page_align_up.asm

**Comment by akasei** [comment]
To jest mój słowotwór ;) Zmienię przy następnej okazji.

**Comment by akasei** [comment]
Poprawione.
