### ISSUE TITLE
Nie da się zbudować moko

### ISSUE THREAD

**Issue by asmodz** [akasei/Cyjon#6]
Jest problem z kompilacją pliku moko.asm, prawdopodobnie nie ma w repo jakiegoś pliku z makrami.
Oto log:
# ====================================
$ make
nasm -f bin software/init.asm -o init.bin
nasm -f bin software/login.asm -o login.bin
nasm -f bin software/shell.asm -o shell.bin
nasm -f bin software/help.asm -o help.bin
nasm -f bin software/uptime.asm -o uptime.bin
nasm -f bin software/moko.asm -o moko.bin
software/moko.asm:22: error: symbol `VARIABLE_MEMORY_HIGH_REAL_ADDRESS' not defined before use
software/moko.asm:22: error: No or invalid offset specified in ORG directive.
# ====================================
Po zdefiniowaniu makra VARIABLE_MEMORY_HIGH_REAL_ADDRESS na pałe na wartosć 0x0
Sypie tym (Wklejam kawałek bo więcej tego jest)
# ====================================
software/moko.asm:48: error: symbol `VARIABLE_ASCII_CODE_ENTER' undefined
software/moko/init.asm:56: error: symbol `VARIABLE_COLOR_BACKGROUND_DEFAULT' undefined
software/moko/init.asm:59: error: symbol `VARIABLE_COLOR_DEFAULT' undefined
software/moko/init.asm:69: error: symbol `VARIABLE_COLOR_BACKGROUND_DEFAULT' undefined
software/moko/init.asm:70: error: symbol `VARIABLE_COLOR_DEFAULT' undefined
software/moko/init.asm:100: error: symbol `VARIABLE_COLOR_BACKGROUND_DEFAULT' undefined
software/moko/init.asm:102: error: symbol `VARIABLE_COLOR_DEFAULT' undefined
software/moko/key_enter.asm:19: error: symbol `VARIABLE_ASCII_CODE_NEWLINE' undefined
software/moko/function_key_read_file.asm:237: error: symbol `VARIABLE_ASCII_CODE_TERMINATOR' undefined
software/moko/function_key_read_file.asm:239: error: symbol `VARIABLE_ASCII_CODE_TERMINATOR' undefined
software/moko/function_key_save.asm:35: error: symbol `VARIABLE_COLOR_BACKGROUND_DEFAULT' undefined
software/moko/function_key_save.asm:45: error: symbol `VARIABLE_COLOR_DEFAULT' undefined
software/moko/function_key_save.asm:47: error: symbol `VARIABLE_COLOR_BACKGROUND_DEFAULT' undefined
software/moko/function_key_save.asm:52: error: symbol `VARIABLE_COLOR_DEFAULT' undefined
software/moko/function_key_save.asm:58: error: symbol `VARIABLE_COLOR_BACKGROUND_DEFAULT' undefined
software/moko/function_key_save.asm:77: error: symbol `VARIABLE_COLOR_DEFAULT' undefined
# ====================================
Sprawdziłem czy makro VARIABLE_COLOR_BACKGROUND_DEFAULT jest gdziekolwiek zdefiniowane 
$ grep -r "VARIABLE_COLOR_BACKGROUND_DEFAULT"
I tak jak przypuszczałem nie ma nigdzie jego definicji, tylko same użycia.
# ====================================
software/moko/init.asm:	mov	rbx,	VARIABLE_COLOR_BACKGROUND_DEFAULT
software/moko/init.asm:	mov	rbx,	VARIABLE_COLOR_BACKGROUND_DEFAULT
software/moko/init.asm:	mov	rbx,	VARIABLE_COLOR_BACKGROUND_DEFAULT
software/moko/the_show_must_go_on.asm:	mov	rdx,	VARIABLE_COLOR_BACKGROUND_DEFAULT
software/moko/the_show_must_go_on.asm:	mov	rdx,	VARIABLE_COLOR_BACKGROUND_DEFAULT
software/moko/the_show_must_go_on.asm:	mov	rdx,	VARIABLE_COLOR_BACKGROUND_DEFAULT
software/moko/function_key_exit.asm:	mov	rdx,	VARIABLE_COLOR_BACKGROUND_DEFAULT
software/moko/save_char_into_document.asm:	mov	rbx,	VARIABLE_COLOR_BACKGROUND_DEFAULT	; czcionka
software/moko/function_key_save.asm:	mov	r8,	VARIABLE_COLOR_BACKGROUND_DEFAULT	; szare tło
software/moko/function_key_save.asm:	mov	rdx,	VARIABLE_COLOR_BACKGROUND_DEFAULT
software/moko/function_key_save.asm:	mov	rdx,	VARIABLE_COLOR_BACKGROUND_DEFAULT
software/moko/function_key_save.asm:	mov	r8,	VARIABLE_COLOR_BACKGROUND_DEFAULT
software/moko/function_key_save.asm:	mov	r8,	VARIABLE_COLOR_BACKGROUND_DEFAULT
software/moko/function_key_save.asm:	mov	r8,	VARIABLE_COLOR_BACKGROUND_DEFAULT	; szare tło
software/moko/function_key_save.asm:	mov	rdx,	VARIABLE_COLOR_BACKGROUND_DEFAULT
# ====================================
Rozwiązałem problem komentując linię która kompiluje plik moko.asm z mejka, oraz tworząc pustą binarke moko.bin, aczkolwiek prosze o dorzucenie pliczku bo myślałem czy by może jakiegoś programu nie skrobnąć pod Cyjona.
Pozdrawiam.

**Comment by akasei** [comment]
Ugh, wieczorem wszystko poprawię, niewygodnie się pracuje na paru stanowiskach: > (nie każde ma prawo dostępu do neta, więc synchronizacja kuleje)

**Comment by akasei** [comment]
Poprawione.
